### ISSUE TITLE
Unique slugs generation

### ISSUE THREAD

**Issue by yoeunes** [zta9taw/utils-bundle#2]
It will be cool if you create unique slugs here : 

https://github.com/zta9taw/utils-bundle/blob/fada9a00a31ed61b34aea8b6e61e9072ba68e720/EventListener/Doctrine/SluggableEntityListener.php#L22

**Comment by zta9taw** [comment]
The principle is to rely on the returned value of the 'getPlainValue' method, so it is up to the developer to manage the uniqueness
